# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ethan Rosenthal
tagline:          blog for ethan rosenthal
url:              http://blog.ethanrosenthal.com
paginate:         1
baseurl:          /
author:
  name:           Ethan Rosenthal
  url:            https://twitter.com/eprosenthal

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ethanrosenthal/blog

# Header links
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

